### ISSUE TITLE
uMatrix installs itself even if you haven't checked the addon

### ISSUE THREAD

**Issue by ghost** [allo-/ffprofile#232]
i just made a new profile to get rid of this persisting ~~garbage~~ of an extension and to my surprise, it reinstalled itself, though I have deleted everything on my profile folder + I haven't checked it on the ffprofile website

**Comment by km-ch** [comment]
> Duplicate of #233.

Oops, for some reason GitHub mobile decided to make a fucky wucky and sent the same issue twice. Sorry(?)
