### ISSUE TITLE
Find a better project name?

### ISSUE THREAD

**Issue by allo-** [allo-/ffprofile#260]
I wonder if we can find a nice new profile name.

Firefox profile maker sounds a bit cumbersome, and it may sound a bit too official with Firefox in front of it. It is a Firefox-profile maker, not a Firefox profile-maker. I didn't hear from Mozilla about that, but I would understand if they don't really like it like that.

I think of "Profile Creator for Firefox" or something similar for the website. Maybe the project should just be called "ffprofile"?

**Comment by seanpm2001** [comment]
Maybe you should put it up to a vote between `Profile Creator for Firefox` and `FFprofile` enabling GitHub discussions would allow the community to vote on the name.

**Comment by allo-** [comment]
As long as there are so few answers (what is *your* preference?) I would start with this issue.

Enabling discussions would have the same problem like the subreddit and the Mastodon account. I do not have much time to look into the related social media and especially not for personal support requests.

**Comment by seanpm2001** [comment]
I think `Profile Creator for Firefox` would be a good name.

**Comment by allo-** [comment]
Let's use ffprofile for now.
