### ISSUE TITLE
Enterprise Policy not working

### ISSUE THREAD

**Issue by snffffffAHHH** [allo-/ffprofile#281]
I run windows 10 iot ltsc. I have installed firefox 115.6.0esr. I assume the "installation folder" is: C:\Users\<my_username>\AppData\Roaming\Mozilla\Firefox
I have unzipped the enterprise policy there and nothing happens. I still have the sign in option in settings menu. The alt menu isn't showing either. Browser updates are still automatic

**Comment by allo-** [comment]
Visit `about:policies` and see if you've installed the policies correctly.

**Comment by snffffffAHHH** [comment]
> Visit `about:policies` and see if you've installed the policies correctly.
> 
> Installation folder does not mean profile folder, but actually the Firefox installation folder.

Profile folder wold be that path above and appended \Profiles. My question is what is the firefox install folder if it's not the root above? It's not in the Mozilla folder either

**Comment by allo-** [comment]
Your path is inside your home folder. Look at c:\Program Files\Mozilla\Firefox or something like that.

**Comment by snffffffAHHH** [comment]
> Your path is inside your home folder. Look at c:\Program Files\Mozilla\Firefox or something like that.

Yes I found it now. I thought It was in AppData. Issue resolved.
