### ISSUE TITLE
Getting "The browser is not supported" in Kick 

### ISSUE THREAD

**Issue by Megane0103** [allo-/ffprofile#290]
![Screenshot 2024-06-26 225905](https://github.com/allo-/ffprofile/assets/99014543/223b82ad-133e-4220-a907-ea82ec4ba16c)

And these are the settings i chose: 
[prefs.json](https://github.com/user-attachments/files/15996460/prefs.json)

**Comment by allo-** [comment]
Try to change the useragent override to something more recent and look in the browser console if there are error messages what disabled feature the site may be trying to use.

**Comment by Megane0103** [comment]
The issue was resolved without doing anything.
