### ISSUE TITLE
Disable "Privacy-Preserving" Attribution

### ISSUE THREAD

**Issue by allo-** [allo-/ffprofile#291]
I need to figure out the about:config setting after installing FF128, as only the checkbox in the settings is mentioned in the official documentation and the blog posts I could find so far.

**Comment by zedd-0** [comment]
dom.private-attribution.submission.enabled
false

how to:
- download FFx portable
- go to 'about:config' & select 'only changed settings'
- try to remove everything
- open second window & go to the settings
- toggle switch and look for changes

**Comment by allo-** [comment]
Thanks. The setting was already added here: https://github.com/allo-/ffprofile/commit/86c5653dfb9fbcb03884278d664ca936fecf1e72

For how to use the generated profile, see the "Finish" page for the different downloads and the raw config options.
