### ISSUE TITLE
[Question] incomplete prefs collection for disabling telemetry?

### ISSUE THREAD

**Issue by mpeter50** [allo-/ffprofile#295]
When I generate a profile with no settings other than disabling telemetry, the resulting prefs.js will contain these lines:
```js
user_pref("toolkit.telemetry.archive.enabled", false);
user_pref("toolkit.telemetry.bhrPing.enabled", false);
user_pref("toolkit.telemetry.cachedClientID", "");
user_pref("toolkit.telemetry.enabled", false);
user_pref("toolkit.telemetry.firstShutdownPing.enabled", false);
user_pref("toolkit.telemetry.hybridContent.enabled", false);
user_pref("toolkit.telemetry.newProfilePing.enabled", false);
user_pref("toolkit.telemetry.prompted", 2);
user_pref("toolkit.telemetry.rejected", true);
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("toolkit.telemetry.server", "");
user_pref("toolkit.telemetry.shutdownPingSender.enabled", false);
user_pref("toolkit.telemetry.unified", false);
user_pref("toolkit.telemetry.unifiedIsOptIn", false);
user_pref("toolkit.telemetry.updatePing.enabled", false);
```

However the Enterprise Policy documentation on the [DisableTemeletry policy](https://mozilla.github.io/policy-templates/#disabletelemetry) says that it affects these preferences:
- `datareporting.healthreport.uploadEnabled`
- `datareporting.policy.dataSubmissionEnabled`
- `toolkit.telemetry.archive.enabled`

The first two are not included in the `prefs.js`. Are they known to be unneeded?

**Comment by allo-** [comment]
You need either prefs or the policy. The preferences are how most people would configure Firefox and how it stores the settings itself and the policy is a way to enforce certain settings system-wide.

prefs:
- Works like when the user changed the settings
- Can freely be changed back
- Leaves often more nuanced options
- Requires unpacking the archive in a newly created profile

policy:
- Enforced for all profiles on the computer
- Settings cannot be changed back in the prefs.js of individual profiles
- Provides only options for most important settings available
- Is applied to every new profile automatically

**Comment by mpeter50** [comment]
Yeah, I assumed policies just make some settings global, so I did not apply them. Being able to only download the prefs also implies that I think.
Besides, sometimes you dont want to use policies because you only want settings for a specific profile.

I think it would be better if everything (that is possible) would be set in the prefs too.

**Comment by allo-** [comment]
> @allo- I think that's important for user to know, maybe put it somewhere

I guess the main zip should be marked as "Use This!" and the others are optional alternatives. See #296 for adding better explanations.

> Yeah, I assumed policies just make some settings global, so I did not apply them. Being able to only download the prefs also implies that I think.

The usual zip contains everything you only need the policies in addition for a few settings that are not exposed as about:config settings.

Policies are another method to apply certain settings. They are more limited, but for administrators who want to preconfigure things on their company's computers the cleaner method than distributing zipped profiles.
