### ISSUE TITLE
How to use Profilemaker on an existing account?

### ISSUE THREAD

**Issue by SquidSalad69** [allo-/ffprofile#298]
I have been using firefox for a while and I discovered the profilemaker not so long ago. I understand it can be used to make a new profile with different defaults but is it possible to use it with an existing profile and use it to update settings instead of wiping my data?

**Comment by allo-** [comment]
You can click "Download prefs.js" on the last page and get the settings for the prefs.js file in your existing profile. I am not sure how Firefox handles duplicate keys, so you need to remove lines for these settings when you want to be sure not to break anything, but probably it just uses the last (or first) occurrence of a key if concatenate multiple preferences files.

Related site feature issue: #25.
And maybe we keep this question in #297.

**Comment by SquidSalad69** [comment]
Oh ok ty, but how do I apply them, clicking the file results in a
javascript runtime error

**Comment by allo-** [comment]
> Oh ok ty, but how do I apply them, clicking the file results in a javascript runtime error

In Firefox when you have the concatenated configs? Then you will have to remove the existing items with the same name. Alternatively you can search in about:config for each item and manually set the value. the prefs.js Download is the same as the preview on the finish page, so you don't need to download it if you only want to copy the values.
